OrdererOrgs:
  - Name: Orderer
    Domain: pharma-network.com
    Specs:
      - Hostname: orderer
      
PeerOrgs:
 - Name: sunpharma
   Domain: sunpharma.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1

 - Name: vgpharma
   Domain: vgpharma.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1

 - Name: upgrad
   Domain: upgrad.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1

 - Name: fedex
   Domain: fedex.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1

 - Name: pioneeratlantic
   Domain: pioneeratlantic.pharma-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
