version: '2'

volumes:
  orderer.pharma-network.com:
  peer0.sunpharma.pharma-network.com:
  peer1.sunpharma.pharma-network.com:
  peer0.vgpharma.pharma-network.com:
  peer1.vgpharma.pharma-network.com:
  peer0.upgrad.pharma-network.com:
  peer1.upgrad.pharma-network.com:
  peer0.fedex.pharma-network.com:
  peer1.fedex.pharma-network.com:
  peer0.pioneeratlantic.pharma-network.com:
  peer1.pioneeratlantic.pharma-network.com:

networks: 
  pharma: ~

services:
  - ca.sunpharma.pharma-network.com

  - ca.vgpharma.pharma-network.com

  - ca.upgrad.pharma-network.com

  - ca.fedex.pharma-network.com

  - ca.pioneeratlantic.pharma-network.com

  - orderer.pharma-network.com

  - peer0.sunpharma.pharma-network.com

  - peer1.sunpharma.pharma-network.com

  - peer0.vgpharma.pharma-network.com

  - peer1.vgpharma.pharma-network.com

  - peer0.upgrad.pharma-network.com

  - peer1.upgrad.pharma-network.com

  - peer0.fedex.pharma-network.com

  - peer1.fedex.pharma-network.com

  - peer0.pioneeratlantic.pharma-network.com
  
  - peer1.pioneeratlantic.pharma-network.com

  ca.fedex.pharma-network.com: 
    command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
    container_name: ca.fedex.pharma-network.com
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vg-pharma.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    image: "hyperledger/fabric-ca:latest"
    networks: 
      - pharma
    ports: 
      - "10054:7054"
    volumes: 
      - "./crypto-config/peerOrganizations/fedex.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config"

  ca.pioneeratlantic.pharma-network.com: 
    command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
    container_name: ca.pioneeratlantic.pharma-network.com
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.pioneeratlantic.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    image: "hyperledger/fabric-ca:latest"
    networks: 
      - pharma
    ports: 
      - "11054:7054"
    volumes: 
      - "./crypto-config/peerOrganizations/pioneeratlantic.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config"
  ca.sunpharma.pharma-network.com: 
    command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
    container_name: ca.sunpharma.pharma-network.com
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sunpharma.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    image: "hyperledger/fabric-ca:latest"
    networks: 
      - pharma
    ports: 
      - "7054:7054"
    volumes: 
      - "./crypto-config/peerOrganizations/sunpharma.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config"
  
  ca.upgrad.pharma-network.com: 
    command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
    container_name: ca.upgrad.pharma-network.com
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.upgrad.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    image: "hyperledger/fabric-ca:latest"
    networks: 
      - pharma
    ports: 
      - "9054:7054"
    volumes: 
      - "./crypto-config/peerOrganizations/upgrad.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config"
  ca.vgpharma.pharma-network.com: 
    command: "sh -c 'fabric-ca-server start -b admin:adminpw -d'"
    container_name: ca.vgpharma.pharma-network.com
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vgpharma.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    image: "hyperledger/fabric-ca:latest"
    networks: 
      - pharma
    ports: 
      - "8054:7054"
    volumes: 
      - "./crypto-config/peerOrganizations/vgpharma.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config"
    
  chaincode: 
    command: "/bin/bash -c 'sleep 6000000'"
    container_name: chaincode
    environment: 
      - GOPATH=/opt/gopath
      - "CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock"
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - "CORE_PEER_ADDRESS=peer0.sunpharma.pharma-network.com:7051"
      - CORE_PEER_LOCALMSPID=sunpharmaMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/sunpharma.pharma-network.com/users/Admin@sunpharma.pharma-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/sunpharma.pharma-network.com/users/Admin@sunpharma.pharma-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/sunpharma.pharma-network.com/users/Admin@sunpharma.pharma-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/sunpharma.pharma-network.com/users/Admin@sunpharma.pharma-network.com/tls/ca.crt
    image: "hyperledger/fabric-ccenv:latest"
    networks: 
      - pharma
    tty: true
    volumes: 
      - "/var/run/:/host/var/run/"
      - "./../chaincode:/opt/gopath/src/chaincode"
      - "./../chaincode-advanced:/opt/gopath/src/chaincode-advanced"
      - "./crypto-config:/opt/gopath/src/crypto"
    working_dir: /opt/gopath/src/chaincode

  cli: 
    command: /bin/bash
    container_name: cli
    depends_on: 
      - ca.sunpharma.pharma-network.com
      - ca.vgpharma.pharma-network.com
      - ca.upgrad.pharma-network.com
      - ca.fedex.pharma-network.com
      - ca.pioneeratlantic.pharma-network.com
      - orderer.pharma-network.com
      - peer0.sunpharma.pharma-network.com
      - peer1.sunpharma.pharma-network.com
      - peer0.vgpharma.pharma-network.com
      - peer1.vgpharma.pharma-network.com
      - peer0.upgrad.pharma-network.com
      - peer1.upgrad.pharma-network.com
      - peer0.fedex.pharma-network.com
      - peer1.fedex.pharma-network.com
      - peer0.pioneeratlantic.pharma-network.com
      - peer1.pioneeratlantic.pharma-network.com
    environment: 
      - GOPATH=/opt/gopath
      - "CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock"
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - "CORE_PEER_ADDRESS=peer0.sun-pharma.pharma-network.com:7051"
      - CORE_PEER_LOCALMSPID=sun-pharmaMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sunpharma.pharma-network.com/peers/peer0.sunpharma.pharma-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sunpharma.pharma-network.com/peers/peer0.sunpharma.pharma-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sunpharma.pharma-network.com/peers/peer0.sunpharma.pharma-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sunpharma.pharma-network.com/users/Admin@sunpharma.pharma-network.com/msp
    image: "hyperledger/fabric-tools:latest"
    networks: 
      - pharma
    stdin_open: true
    tty: true
    volumes: 
      - "/var/run/:/host/var/run/"
      - "./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/"
      - "./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/"
      - "./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/"
      - "./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer

  orderer.pharma-network.com: 
    container_name: orderer.pharma-network.com
    extends: 
    file: docker-base/docker-compose-base.yaml
    service: orderer.pharma-network.com
    networks: 
      - pharma
    peer0.fedex.pharma-network.com: 
      container_name: peer0.fedex.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer0.fedex.pharma-network.com
      networks: 
        - pharma
    peer0.pioneeratlantic.pharma-network.com: 
      container_name: peer0.pioneeratlantic.pharma-network.com
      extends: 
        file: docker-base/dockercompose-base.yaml
        service: peer0.pioneeratlantic.pharma-network.com
      networks: 
        - pharma
    peer0.sunpharma.pharma-network.com: 
      container_name: peer0.sunpharma.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer0.sunpharma.pharma-network.com
      networks: 
        - pharma
    peer0.upgrad.pharma-network.com: 
      container_name: peer0.upgrad.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer0.upgrad.pharma-network.com
      networks: 
        - pharma
    peer0.vgpharma.pharma-network.com: 
      container_name: peer0.vgpharma.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer0.vgpharma.pharma-network.com
      networks: 
        - pharma
    peer1.fedex.pharma-network.com: 
      container_name: peer1.fedex.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer1.fedex.pharma-network.com
      networks: 
        - pharma
    peer1.pioneeratlantic.pharma-network.com: 
      container_name: peer1.pioneeratlantic.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer1.pioneeratlantic.pharma-network.com
      networks: 
        - pharma
    peer1.sunpharma.pharma-network.com: 
      container_name: peer1.sunpharma.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer1.sunpharma.pharma-network.com
      networks: 
        - pharma
    peer1.upgrad.pharma-network.com: 
      container_name: peer1.upgrad.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer1.upgrad.pharma-network.com
      networks: 
        - pharma
    peer1.vgpharma.pharma-network.com: 
      container_name: peer1.vgpharma.pharma-network.com
      extends: 
        file: docker-base/docker-compose-base.yaml
        service: peer1.vgpharma.pharma-network.com
      networks: 
        - pharma

  